name: timetable_app
description: A Flutter app to manage daily timetables.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" # Ensure compatibility with Dart 3.0+

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3 # For local storage
  hive_flutter: ^1.1.0 # Flutter integration for Hive
  provider: ^6.1.3 # For state management
  intl: ^0.18.1 # For date and time formatting
  flutter_local_notifications: ^15.1.3
  timezone: ^0.9.4
  permission_handler: ^12.0.0+1 # Updated version
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3 # Code generation for Hive
  build_runner: ^2.4.6 # For generating Hive adapters
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
